"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga backend/.env si existe (no versionado — ver .env.example). En el
# servidor de producción las variables se setean por otro medio y esto es un
# no-op silencioso.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En producción (Render) se setea vía la variable de entorno SECRET_KEY; sin
# ella, cae al valor de desarrollo de siempre para no romper el flujo local.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-nmv4fh7^u+g67bur-)sy#+b81npkyqs1wtjkj+q2$%9bbdq&l^',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Desarrollo: además de localhost, se permite la IP LAN del PC para poder
# probar desde un celular físico conectado a la misma red WiFi
# (`python manage.py runserver 0.0.0.0:8000`).
#
# Producción: Render inyecta RENDER_EXTERNAL_HOSTNAME solo (el dominio
# *.onrender.com del propio servicio), así que no hace falta setear nada a
# mano para el caso normal. ALLOWED_HOSTS como variable de entorno queda para
# el caso de agregar un dominio propio más adelante.
_allowed_hosts_env = os.environ.get('ALLOWED_HOSTS')
_render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')

if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
elif _render_hostname:
    ALLOWED_HOSTS = [_render_hostname]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.186', '10.0.2.2']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'solicitudes',
    'roles',
    'gamificacion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if not DEBUG:
    # Sirve /static/ directamente desde gunicorn en producción (Render no
    # tiene un servidor web separado delante como nginx). En dev, runserver
    # ya sirve estáticos vía `django.contrib.staticfiles` sin esto — y sin
    # STATIC_ROOT todavía poblado por `collectstatic`, WhiteNoise emite un
    # warning al arrancar.
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# En producción (Render) se setea DATABASE_URL apuntando al pooler de
# Supabase; sin esa variable, cae al Postgres local de siempre para no romper
# el flujo de desarrollo (`python manage.py test solicitudes`, etc.).
_database_url = os.environ.get('DATABASE_URL')

if _database_url:
    DATABASES = {
        'default': dj_database_url.parse(_database_url, ssl_require=True),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'recicladora',       # Nombre de la base de datos que creaste en pgAdmin
            'USER': 'postgres',            # Tu usuario de PostgreSQL (por defecto es postgres)
            'PASSWORD': 'postgres',     # La contraseña que usas para entrar a pgAdmin/Postgres
            'HOST': 'localhost',           # O '127.0.0.1'
            'PORT': '5432',                # Puerto estándar de PostgreSQL
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # destino de `collectstatic` en producción


# Media files (fotos subidas por los usuarios)
# https://docs.djangoproject.com/en/6.1/topics/files/
#
# Render no ofrece disco persistente en sus planes estándar (el filesystem se
# reinicia en cada deploy), así que en producción el storage por defecto pasa
# a ser el bucket S3-compatible de Supabase Storage en vez de MEDIA_ROOT local.
# Se activa solo si las 4 variables SUPABASE_S3_* están presentes; si no,
# sigue sirviendo desde disco local como en desarrollo.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

AWS_S3_ENDPOINT_URL = os.environ.get('SUPABASE_S3_ENDPOINT', '')
AWS_ACCESS_KEY_ID = os.environ.get('SUPABASE_S3_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('SUPABASE_S3_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.environ.get('SUPABASE_S3_BUCKET', '')

_usando_supabase_storage = bool(
    AWS_S3_ENDPOINT_URL and AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME
)

if _usando_supabase_storage:
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    DEFAULT_FILE_STORAGE_BACKEND = 'storages.backends.s3.S3Storage'

    # El endpoint S3 (`<ref>.storage.supabase.co/storage/v1/s3`) exige firma
    # SigV4 en cada GET, incluso en un bucket público ("Missing signature") —
    # sólo la REST API propia de Storage, en el subdominio sin "storage."
    # (`<ref>.supabase.co/storage/v1/object/public/<bucket>`), sirve lectura
    # anónima. Sin este override, `foto.url` apunta al endpoint S3 y da 403.
    _supabase_public_host = urlparse(AWS_S3_ENDPOINT_URL).netloc.replace(
        '.storage.supabase.co', '.supabase.co'
    )
    AWS_S3_CUSTOM_DOMAIN = (
        f'{_supabase_public_host}/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}'
    )
else:
    DEFAULT_FILE_STORAGE_BACKEND = 'django.core.files.storage.FileSystemStorage'

# WhiteNoise comprime y versiona los estáticos, pero requiere `collectstatic`
# corrido de antemano — en desarrollo (DEBUG=True) eso no pasa, así que ahí se
# usa el storage plano de siempre y Django sigue sirviendo /static/ como hoy.
STORAGES = {
    'default': {
        'BACKEND': DEFAULT_FILE_STORAGE_BACKEND,
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    # Límites del Flujo 5 (recuperación de contraseña) — evitan que alguien
    # agote la bandeja de correo de un tercero o fuerce el código por fuerza
    # bruta. Sin scope, ScopedRateThrottle no limita nada (solo actúa sobre
    # vistas que declaran `throttle_scope`), así que el resto de la API sigue
    # sin límites propios por ahora.
    'DEFAULT_THROTTLE_RATES': {
        'recuperacion-solicitar': '5/hour',
        'recuperacion-verificar': '20/hour',
    },
}

# CORS (desarrollo): permitir la app Flutter (emulador/web) sin restricciones de origen.
CORS_ALLOW_ALL_ORIGINS = DEBUG


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Envío vía la API HTTP de Resend (`config.mail_backends.ResendAPIEmailBackend`),
# no su relay SMTP: Render bloquea el tráfico saliente a los puertos SMTP en
# sus planes free, lo que colgaba el request hasta que gunicorn mataba el
# worker por timeout (ver docs/plan-despliegue.md). La API key vive en
# backend/.env (no versionado, ver .env.example).
#
# Sin RESEND_API_KEY seteada (p. ej. clonando el repo por primera vez) cae al
# backend de consola, así el Flujo 5 (recuperación de contraseña) se puede
# probar imprimiendo el correo en la terminal de `runserver` sin credenciales.
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')

if RESEND_API_KEY:
    EMAIL_BACKEND = 'config.mail_backends.ResendAPIEmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', 'EcoRecicla <no-reply@ecorecicla.local>'
)

# Ventana de expiración/reenvío/intentos del código OTP de recuperación
# (Flujo 5 — ver docs/flujo-5-inicio-registro-recuperacion/).
RECUPERACION_OTP_EXPIRA_MINUTOS = 10
RECUPERACION_OTP_REENVIO_COOLDOWN_SEGUNDOS = 30
RECUPERACION_OTP_MAX_INTENTOS = 5
