"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga backend/.env si existe (no versionado — ver .env.example). En el
# servidor de producción las variables se setean por otro medio y esto es un
# no-op silencioso.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nmv4fh7^u+g67bur-)sy#+b81npkyqs1wtjkj+q2$%9bbdq&l^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Desarrollo: además de localhost, se permite la IP LAN del PC para poder
# probar desde un celular físico conectado a la misma red WiFi
# (`python manage.py runserver 0.0.0.0:8000`).
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.186', '10.0.2.2']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'solicitudes',
    'roles',
    'gamificacion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'recicladora',       # Nombre de la base de datos que creaste en pgAdmin
        'USER': 'postgres',            # Tu usuario de PostgreSQL (por defecto es postgres)
        'PASSWORD': 'postgres',     # La contraseña que usas para entrar a pgAdmin/Postgres
        'HOST': 'localhost',           # O '127.0.0.1'
        'PORT': '5432',                # Puerto estándar de PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Media files (fotos subidas por los usuarios)
# https://docs.djangoproject.com/en/6.1/topics/files/

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    # Límites del Flujo 5 (recuperación de contraseña) — evitan que alguien
    # agote la bandeja de correo de un tercero o fuerce el código por fuerza
    # bruta. Sin scope, ScopedRateThrottle no limita nada (solo actúa sobre
    # vistas que declaran `throttle_scope`), así que el resto de la API sigue
    # sin límites propios por ahora.
    'DEFAULT_THROTTLE_RATES': {
        'recuperacion-solicitar': '5/hour',
        'recuperacion-verificar': '20/hour',
    },
}

# CORS (desarrollo): permitir la app Flutter (emulador/web) sin restricciones de origen.
CORS_ALLOW_ALL_ORIGINS = DEBUG


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Envío vía Resend usando su SMTP relay (smtp.resend.com), así no hace falta
# el SDK de Resend ni django-anymail: el backend SMTP estándar de Django ya
# sirve. La API key vive en backend/.env (no versionado, ver .env.example) y
# se toma como password SMTP — el usuario es literalmente "resend".
#
# Sin RESEND_API_KEY seteada (p. ej. clonando el repo por primera vez) cae al
# backend de consola, así el Flujo 5 (recuperación de contraseña) se puede
# probar imprimiendo el correo en la terminal de `runserver` sin credenciales.
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')

if RESEND_API_KEY:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.resend.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'resend'
    EMAIL_HOST_PASSWORD = RESEND_API_KEY
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', 'EcoRecicla <no-reply@ecorecicla.local>'
)

# Ventana de expiración/reenvío/intentos del código OTP de recuperación
# (Flujo 5 — ver docs/flujo-5-inicio-registro-recuperacion/).
RECUPERACION_OTP_EXPIRA_MINUTOS = 10
RECUPERACION_OTP_REENVIO_COOLDOWN_SEGUNDOS = 30
RECUPERACION_OTP_MAX_INTENTOS = 5
