# Generated by Django 6.1 on 2026-09-07 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0003_solicitudretiro_peso_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recompensas/')),
                ('costo_puntos', models.PositiveIntegerField()),
                ('categoria', models.CharField(choices=[('descuentos', 'Descuentos'), ('productos', 'Productos'), ('servicios', 'Servicios')], default='productos', max_length=20)),
                ('comercio_nombre', models.CharField(blank=True, max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['costo_puntos'],
            },
        ),
        migrations.CreateModel(
            name='EventoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acreditacion', 'Acreditación de EcoPuntos'), ('hito_racha', 'Hito de racha')], max_length=20)),
                ('payload', models.JSONField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('visto_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_pendientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_gastados', models.PositiveIntegerField()),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to=settings.AUTH_USER_MODEL)),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canjes', to='gamificacion.recompensa')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SaldoEcoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_ecopuntos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionEcoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acreditacion', 'Acreditación por reciclaje'), ('bono_racha', 'Bono de racha'), ('canje', 'Canje de recompensa')], max_length=20)),
                ('puntos', models.IntegerField()),
                ('racha_semanas', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('canje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion', to='gamificacion.canje')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_ecopuntos', to='solicitudes.solicitudretiro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_ecopuntos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoRacha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ciudadano', 'Ciudadano'), ('recolector', 'Recolector')], max_length=20)),
                ('racha_actual', models.PositiveIntegerField(default=0)),
                ('racha_maxima', models.PositiveIntegerField(default=0)),
                ('protectores_disponibles', models.PositiveSmallIntegerField(default=2)),
                ('mes_protectores', models.DateField()),
                ('semana_evaluada_hasta', models.DateField(blank=True, null=True)),
                ('ultimo_hito_acreditado', models.PositiveIntegerField(default=0)),
                ('hito_pendiente_de_mostrar', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_racha', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de racha',
                'verbose_name_plural': 'Progresos de racha',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'rol'), name='progreso_racha_unico_por_rol')],
            },
        ),
    ]
