# Generated by Django 6.1 on 2026-08-25 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


TABLA = 'solicitudes_solicitudretiro'


def migrar_recolectores_a_perfil(apps, schema_editor):
    """
    Hasta la 0001 `SolicitudRetiro.recolector` apuntaba directamente a User.
    Se crea un perfil `Recolector` por cada usuario referenciado y se reescribe
    la columna para que apunte al perfil antes de cambiar la FK de destino.
    """
    Recolector = apps.get_model('solicitudes', 'Recolector')

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f'SELECT id, recolector_id FROM {TABLA} WHERE recolector_id IS NOT NULL'
        )
        filas = cursor.fetchall()

        # Se resuelven todos los perfiles antes de escribir: si se actualizara
        # fila por fila, un id de perfil podría chocar con un id de usuario
        # todavía sin migrar.
        perfiles = {}
        for _, usuario_id in filas:
            if usuario_id not in perfiles:
                perfil, _creado = Recolector.objects.get_or_create(usuario_id=usuario_id)
                perfiles[usuario_id] = perfil.id

        for solicitud_id, usuario_id in filas:
            cursor.execute(
                f'UPDATE {TABLA} SET recolector_id = %s WHERE id = %s',
                [perfiles[usuario_id], solicitud_id],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudretiro',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='solicitudretiro',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Recolector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_activo', models.BooleanField(default=False)),
                ('latitud_actual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_actual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ultimo_ping', models.DateTimeField(auto_now=True)),
                ('total_completadas', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_recolector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recolector',
                'verbose_name_plural': 'Recolectores',
            },
        ),
        migrations.CreateModel(
            name='AsignacionRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('aceptada', 'Aceptada'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='aceptada', max_length=20)),
                ('aceptada_en', models.DateTimeField(auto_now_add=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='solicitudes.solicitudretiro')),
                ('recolector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='solicitudes.recolector')),
            ],
            options={
                'verbose_name': 'Asignación de Retiro',
                'verbose_name_plural': 'Asignaciones de Retiro',
                'ordering': ['-aceptada_en'],
            },
        ),
        migrations.RunPython(
            migrar_recolectores_a_perfil,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='solicitudretiro',
            name='recolector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to='solicitudes.recolector'),
        ),
    ]
