# Generated by Django 6.1 on 2026-09-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_solicitudretiro_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudretiro',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
