# Generated by Django 6.1.1 on 2026-09-10 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_solicitudretiro_peso_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionretiro',
            name='calificacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='asignacionretiro',
            name='calificacion_comentario',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='asignacionretiro',
            name='calificacion_etiquetas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='asignacionretiro',
            name='en_camino_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacionretiro',
            name='llego_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolector',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='recolectores/'),
        ),
        migrations.AddField(
            model_name='recolector',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudretiro',
            name='estado_coordinacion',
            field=models.CharField(choices=[('pendiente', 'Sin franja'), ('propuesta_ciudadano', 'Propuesta por el ciudadano'), ('propuesta_recolector', 'Propuesta por el recolector'), ('confirmada', 'Confirmada')], default='pendiente', max_length=25),
        ),
        migrations.AddField(
            model_name='solicitudretiro',
            name='franja_confirmada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudretiro',
            name='notas_entrega',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='solicitudretiro',
            name='ventana_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudretiro',
            name='ventana_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
